//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        public Banco()
        {
            this.ChequeArqueo = new HashSet<ChequeArqueo>();
        }
    
        public int bancoId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<ChequeArqueo> ChequeArqueo { get; set; }
    }
}
