//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraDetalle
    {
        public int Cantidad { get; set; }
        public float PrecioUnitario { get; set; }
        public int Compra_CompraID { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
