//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cosecha
    {
        public Cosecha()
        {
            this.CosechaDetalle = new HashSet<CosechaDetalle>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int CosechaId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
    
        public virtual ICollection<CosechaDetalle> CosechaDetalle { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
