//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denominacion
    {
        public Denominacion()
        {
            this.EfectivoArqueo = new HashSet<EfectivoArqueo>();
        }
    
        public int Codigo { get; set; }
        public string Tipo { get; set; }
        public string Denominación { get; set; }
    
        public virtual ICollection<EfectivoArqueo> EfectivoArqueo { get; set; }
    }
}
