//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfectivoArqueo
    {
        public EfectivoArqueo()
        {
            this.ArqueoCajaDetalle = new HashSet<ArqueoCajaDetalle>();
        }
    
        public int EfectivoArqueoID { get; set; }
        public int Denominacion { get; set; }
        public int cantidad { get; set; }
    
        public virtual ICollection<ArqueoCajaDetalle> ArqueoCajaDetalle { get; set; }
        public virtual Denominacion Denominacion1 { get; set; }
    }
}
