//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
            this.Cobros = new HashSet<Cobros>();
        }
    
        public int FacturaID { get; set; }
        public string CodigoFactura { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> ProductorId { get; set; }
        public string TipoFactura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public decimal ValorFactura { get; set; }
        public decimal SaldoPendiente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Productor Productor { get; set; }
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual ICollection<Cobros> Cobros { get; set; }
    }
}
