//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumo
    {
        public Insumo()
        {
            this.Inventario = new HashSet<Inventario>();
            this.PrecioCompra = new HashSet<PrecioCompra>();
            this.CompraDetalle = new HashSet<CompraDetalle>();
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
        }
    
        public int InsumoID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual ICollection<PrecioCompra> PrecioCompra { get; set; }
        public virtual ICollection<CompraDetalle> CompraDetalle { get; set; }
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
    }
}
