//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPrecio
    {
        public ListaPrecio()
        {
            this.PrecioCompra = new HashSet<PrecioCompra>();
            this.PrecioVenta = new HashSet<PrecioVenta>();
            this.Productor = new HashSet<Productor>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<PrecioCompra> PrecioCompra { get; set; }
        public virtual ICollection<PrecioVenta> PrecioVenta { get; set; }
        public virtual ICollection<Productor> Productor { get; set; }
    }
}
