//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotes
    {
        public Lotes()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int LoteId { get; set; }
        public int FincaId { get; set; }
        public string Extencion { get; set; }
        public string TipoSuelo { get; set; }
        public string TipoRiego { get; set; }
        public Nullable<int> CantidadCosecha { get; set; }
    
        public virtual Finca Finca { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
