//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioVenta
    {
        public int PrecioVentaID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public string ListaPrecio { get; set; }
        public Nullable<int> InsumoId { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual ListaPrecio ListaPrecio1 { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
