//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioCompra
    {
        public int precioCompraId { get; set; }
        public string ListaPrecios { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> InsumoId { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public bool esInsumo { get; set; }
        public virtual Insumo Insumo { get; set; }
        public virtual ListaPrecio ListaPrecio { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
