//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productor
    {
        public Productor()
        {
            this.Pagos = new HashSet<Pagos>();
            this.Factura = new HashSet<Factura>();
            this.Finca = new HashSet<Finca>();
        }
    
        public int ProductorID { get; set; }
        public string Nombre { get; set; }
        public string Identidad { get; set; }
        public string RTN { get; set; }
        public string Telefono { get; set; }
        public string EMail { get; set; }
        public Nullable<decimal> SaldoDisponible { get; set; }
        public Nullable<int> DiasCredito { get; set; }
        public int CuentaBancariaID { get; set; }
        public string ListaPrecioID { get; set; }
    
        public virtual CuentaBancaria CuentaBancaria { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<Finca> Finca { get; set; }
        public virtual ListaPrecio ListaPrecio { get; set; }
    }
}
