//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comercializadora.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Inventario = new HashSet<Inventario>();
            this.PrecioCompra = new HashSet<PrecioCompra>();
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
            this.CosechaDetalle = new HashSet<CosechaDetalle>();
            this.PrecioVenta = new HashSet<PrecioVenta>();
        }
    
        public int ProductoID { get; set; }
        public string Descripcion { get; set; }
        public int LoteID { get; set; }
    
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual Lotes Lotes { get; set; }
        public virtual ICollection<PrecioCompra> PrecioCompra { get; set; }
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual ICollection<CosechaDetalle> CosechaDetalle { get; set; }
        public virtual ICollection<PrecioVenta> PrecioVenta { get; set; }
    }
}
